### ISSUE TITLE
I/O CA

### ISSUE THREAD

**Issue by radekmie** [H3MapGenTeam/h3mapgen#21]
### Co?
Napisać wrapper, który będzie pozwalał wywoływać CA bezpośrednio (tj. bez pośrednich **jawnych** plików) z poziomu Lua.

### Dlaczego?
By zapewnić pełną wymienność modułów, każda z części powinna mieć takie samo API - na spotkaniu 2017-11-15 zdecydowaliśmy, że będzie to `h3pgm` -> `h3pgm` (Lua).

**Comment by radekmie** [comment]
Oczekiwane API:

```lua
local world = ca(state, zoneId, ...caArgs)
```

Aktualnie `world` (inaczej `grid`) jest zdefiniowany jako tablica o kluczach `x y z`.

Opracuję też kilka małych testów.

**EDIT:** Powinien też przyjmować (i respektować!) `seed`, żeby w całym procesie był deterministycznym fragmentem.

**Comment by Fanderman** [comment]
Jakiś wstępny termin?

**Comment by acatai** [comment]
Proponuję żeby Pan się do tego taska przymierzył zanim ostatecznie zdecyduje się na ten projekt.
Ja konkretnej sugestii terminu jako takiego nie mam.

**Comment by Fanderman** [comment]
Trochę długo nic nie napisałem, ale teraz tworzę jak ma być. Czy api ma się odwoływać jedynie do funkcji void terrain z cellular_terrain.cpp czy do innych funkcji/plików również?

**Comment by Fanderman** [comment]
Wystawiony pull request.
