### ISSUE TITLE
Get rid of CONFIG global

### ISSUE THREAD

**Issue by radekmie** [H3MapGenTeam/h3mapgen#26]
Plik `Auxiliary/Serialization` wymaga globala `CONFIG`. Powinien dać sobie radę bez.

**Comment by acatai** [comment]
Przy okazji poprawiłbym problemy Serializacji z zapisem stringów które 
- mają sobie w spacje
- parsują się do liczb

Aha, i tak jak ustaliliśmy, rzeczy z `components/Auxiliary` przechodzą do `lib`.

**Comment by acatai** [comment]
Zamknięte przez #49.
