### ISSUE TITLE
Uzupełnić dokumentację o zdjęcia

### ISSUE THREAD

**Issue by acatai** [H3MapGenTeam/h3mapgen#28]
Powrzucać do folderu z dokumentacją historyczne zdjęcia tablic żeby było tematycznie w jednym miejscu bez potrzeby przekopywania się przez tonę maili.

**Comment by acatai** [comment]
@radekmie OK, zdjęcia dodałem, pull requesta nie robiłem bo bez przesady, ale jakbyś rzucił okiem. Najpierw chciałem bez dat ale mogą być jednak istotne...

**Comment by radekmie** [comment]
Jak dla mnie jest OK.

**Comment by acatai** [comment]
OK, no to done. 
Od teraz najlepiej wrzucać od razu tutaj albo będę to robił bezpośrednio po otrzymaniu zdjęć mailem.
