### ISSUE TITLE
Zrobić wstępną wersję GUI dla userów

### ISSUE THREAD

**Issue by acatai** [H3MapGenTeam/h3mapgen#43]
Po ustaleniu zestawu początkowych parametrów (see #37), napisać GUI w którym będzie możliwość tworzenia nowej mapy ustawiając parametry generatora.

Bardziej zaawansowane użycie zakłada możliwość modyfikacji bardziej szczegółowych parametrów (`concrete` i/lub `config`).

Ostatecznie chcielibyśmy też mieć opcję `loadH3PGM`, pozwalającą regenerować poszczególne kroki (see #38).

Ah no i oczywiście 'post-opcje': minimapa, otwórz w edytorze, wklej do folderu z grą, itd.

**Comment by radekmie** [comment]
Robiłem dzisiaj kilka prób: próbowałem wszystkiego [tu](http://lua-users.org/wiki/GraphicalUserInterfaceToolkits) i jest tak:

* nie ma dokumentacji
* jest nieprzenośne
* jest nierozwijane
* nie da się go skompilować z różnych powodów

_wybierz nie mniej niż 1_

**Comment by acatai** [comment]
OK, to kiepsko, bo ja już nawet przygotowałem wstępny projekt GUI do rozpatrzenia :(.

Co proponujesz?
Bo może w takim razie nie powinniśmy kombinować z Lua tylko GUI powinno być w C?

**Comment by radekmie** [comment]
Jest np. [nuklear](https://github.com/vurtun/nuklear). Spróbuję potem.

**Comment by acatai** [comment]
Wygląda efektownie.
Bo też pytanie na ile chcemy się trzymać czystego C, a na ile prościej byłoby skorzystać z czegoś pod C++.

**Comment by radekmie** [comment]
Nie lubię (bardzo) wyglądu qt... Najpierw sprawdzę to.

**Comment by radekmie** [comment]
Jest tak: da się, ale potrzeba GLEW, GLFW i całej rodzinki... Meh.

**Comment by acatai** [comment]
Właściwie #49 definiuje userParams dość porządnie więc nie uznajemy tego taska za blocked ;-).
Na detailedParams przyjdzie jeszcze chwilę poczekać.

**Comment by radekmie** [comment]
Dobra, jest już dość dużo na branchu `gui`. Problem: nie ma jednak dropdowna. Jest np. stepper, czyli wartość z dwoma strzałkami po bokach/góra+dół. Inne pomysły?

**Comment by acatai** [comment]
Szkoda, że nie ma....
Może w takim razi niech będzie ten stepper? Bo na 8 radiobuttonów sobie raczej pozwolić nie możemy ;p.

**Comment by radekmie** [comment]
#53.
