### ISSUE TITLE
Błędy make w homm3lua.

### ISSUE THREAD

**Issue by maciek16180** [H3MapGenTeam/h3mapgen#50]
Na masterze:

maciek@maciek-L560:\~/Desktop/h3/h3mapgen$ git submodule update --init --recursive
maciek@maciek-L560:\~/Desktop/h3/h3mapgen$ make
> make -C libs/homm3lua
make[1]: Entering directory '/home/maciek/Desktop/h3/h3mapgen/libs/homm3lua'
cc homm3lua/homm3lua_constants.c -c -I/usr/include/lua5.3 -W -Wall -Wextra -O3 -fPIC -shared -std=c99 -I homm3tools/h3m/h3mlib -I homm3tools/3rdparty/uthash/src -o dist/homm3lua_constants.o
homm3lua/homm3lua_constants.c: In function ‘h3mlua_constants’:
homm3lua/homm3lua_constants.c:57:38: error: ‘**H3M_HERO_CONFLUX**’ undeclared (first use in this function)
   constant("HERO_CONFLUX",           H3M_HERO_CONFLUX);
                                      ^
homm3lua/homm3lua_constants.c:5:22: note: in definition of macro ‘constant’
   lua_pushinteger(L, value);    \
                      ^
homm3lua/homm3lua_constants.c:57:38: note: each undeclared identifier is reported only once for each function it appears in
   constant("HERO_CONFLUX",           H3M_HERO_CONFLUX);
                                      ^
homm3lua/homm3lua_constants.c:5:22: note: in definition of macro ‘constant’
   lua_pushinteger(L, value);    \
                      ^
homm3lua/homm3lua_constants.c:65:38: error: ‘**H3M_HERO_DARKSTORN**’ undeclared (first use in this function)
   constant("HERO_DARKSTORN",         H3M_HERO_DARKSTORN);
                                      ^
homm3lua/homm3lua_constants.c:5:22: note: in definition of macro ‘constant’
   lua_pushinteger(L, value);    \
                      ^
Makefile:34: recipe for target 'dist/homm3lua_constants.o' failed
make[1]: *** [dist/homm3lua_constants.o] Error 1
make[1]: Leaving directory '/home/maciek/Desktop/h3/h3mapgen/libs/homm3lua'
Makefile:25: recipe for target 'homm3lua' failed
make: *** [homm3lua] Error 2

Próbowałem to zbudować, żeby sprawdzić, czy działa, no i nie działa. Błędy stałych w homm3lua, nie ma takiego herosa DARKSTORN, jest DARKSTORM (w `h3m_hero.h`). HERO_CONFLUX też wygląda dość podejrzanie.

**Comment by radekmie** [comment]
Wygląda na to, że w #49 _ktoś_ mi cofnął commit. Już robię PR.

**Comment by acatai** [comment]
Wydaje się, że tak.
Komuś się pewnie wydawało, że robi coś dobrze. Ktoś przeprasza :(.
Swoją drogą ktoś inny to zatwierdził.
