### ISSUE TITLE
Niejednoznaczności z ustalanym random seedem w parametrach

### ISSUE THREAD

**Issue by acatai** [H3MapGenTeam/h3mapgen#91]
Wydaje mi się, że testując nie generowało mi takich samych map jeśli kopiowałem i wklejałem seeda z `paramsGeneral`. 

Jak rozumiem, chcielibyśmy żeby system generował dokładnie tę samą mapę jeśli:
- ten sam seed został przeklejony do `paramsDetailedUser`  (nie do `paramsDetailed`!)
- pozostałe wartości w `paramsGeneral` nie uległy zmianie.

Czy tak?

**Comment by acatai** [comment]
IMO dalej coś jest nie halo...
Jak odpalam `tests\lml\Test.lua` i wywołuję np. `Test('01', 17)` to za każdym razem generowany LML (w `tests\out\17_4\LML.png`) jest inny.
Tak chyba nie powinno być?

**Comment by radekmie** [comment]
Zgaduję, że `Test('01', 17)` oznacza stan `Test` na Twoim nowym branchu, bo aktualnie ta funkcja ma tylko jeden parametr i działa dobrze, tj. `Params.GenerateDetailedParams(state)` losuje nowy seed, bo `paramsGeneral.seed == 0`.

Przy okazji: ten plik na Linuxie bruździ i nie działa bez poprawek (np. ścieżki).

A teraz powód:

```lua
  for name, weight in pairs(grammar) do
```

Jednak jest jeszcze inaczej z tą kolejnością w `pairs`. Tak, jest deterministyczna. Tak, jest stała w obrębie jednej wersji. Tak, nie zmienia się dla jednego obiektu (wiele `pairs` na tym samym obiekcie daje tę samą kolejność). Ale jest jeden problem: ta kolejność jest różna, w zależności od ułożenia obiektu w pamięci. Także ładowanie obiektów z `config.cfg` jest problematyczne, bo `pairs` na nich nie jest zawsze takie samo.

**Comment by acatai** [comment]
Problem był głównie z powodu użycia `pairs` w `Random.RouletteWheel(map)`.
Done.
